package(default_visibility = ["//visibility:public"])

cc_proto_library(
    name = "test_cc_proto",
    deps = [
        ":test_proto",
    ],
)

proto_library(
    name = "test_proto",
    srcs = ["test.proto"],
)
